name: accra_wkshp_ucl
channels:
    - conda-forge
dependencies:
    - matplotlib
    - pandas
    - scipy
    - python>=3.6
    - gdal>=2.3.0
    - tqdm
    - libgdal>=2.3.0
    - netCDF4
    - pip
    - skimage
    - shapely
    - rasterio
    - bandmat
    - pip:
        - sentinelsat